name: Java CI with Gradle

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/settings.gradle') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup BuildTools (1.8.8 - 1.16.5)
        uses: SpraxDev/Action-SpigotMC@v4.0.0
        with:
          versions: 1.8.8, 1.12.2, 1.13.2, 1.16.5
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew core:build version-support:build version-support1_8:build version-support1_12:build version-support1_13:build version-support1_16:build build
      - uses: actions/upload-artifact@v2
        with:
          name: LyraLibs
          path: |
            core/build/libs/
            bukkit/build/libs/
            velocity/build/libs/


      # Ok, there might be a better way to do this, but idc
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest-core"
          prerelease: true
          title: "Core"
          files: |
            core/build/libs/


      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest-bukkit"
          prerelease: true
          title: "Bukkit"
          files: |
            bukkit/build/libs/normal
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest-velocity"
          prerelease: true
          title: "Velocity"
          files: |
            velocity/build/libs/normal

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest-light-core"
          prerelease: true
          title: "Core-Light"
          files: |
            core/build/libs/
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest-light-bukkit"
          prerelease: true
          title: "Bukkit-Light"
          files: |
            bukkit/build/libs/light
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest-light-velocity"
          prerelease: true
          title: "Velocity-Light"
          files: |
            velocity/build/libs/light