name: Java CI with Gradle

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/settings.gradle') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup BuildTools (1.8.8 - 1.16.5)
        uses: SpraxDev/Action-SpigotMC@v4.0.0
        with:
          versions: 1.8.8, 1.12.2, 1.13.2, 1.16.5
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew core:build version-support:build version-support1_8:build version-support1_12:build version-support1_13:build version-support1_16:build build
      - uses: actions/upload-artifact@v2
        with:
          name: LyraLibs
          path: |
            core/build/libs/
            bukkit/build/libs/
            velocity/build/libs/
