name: Java CI with Gradle

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: BuildTools
        run: |
          mkdir spigot
          cd spigot
          wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.8.8
          java -jar BuildTools.jar --rev 1.12.2
          java -jar BuildTools.jar --rev 1.13.2
          java -jar BuildTools.jar --rev 1.16.5
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Clean artifacts with Gradle
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew core:build version-support:build version-support1_8:build version-support1_13:build version-support1_16:build build
      - uses: actions/upload-artifact@v2
        with:
          name: LyraLibs
          path: |
            bukkit/build/libs/
            velocity/build/libs/
